Add GitHub Actions workflow for Windows build

diff --git a/.github/workflows/windows.yml b/.github/workflows/windows.yml
--- a/.github/workflows/windows.yml
+++ b/.github/workflows/windows.yml
@@ -61,9 +61,9 @@ jobs:
           ls
 
       - name: View Temporary Script
-      shell: bash
-      run: |
-        cat D:\a\_temp\32bbc863-5f2a-40d5-920b-c99877af7c9e.sh || echo "Script not found"
+        shell: bash
+        run: |
+          cat D:\a\_temp\32bbc863-5f2a-40d5-920b-c99877af7c9e.sh || echo "Script not found"
 
 
       - name: Install Building Dependencies
