Add GitHub Actions workflow for Windows build

diff --git a/.github/workflows/windows.yml b/.github/workflows/windows.yml
--- a/.github/workflows/windows.yml
+++ b/.github/workflows/windows.yml
@@ -60,6 +60,12 @@ jobs:
         run: |
           ls
 
+      - name: View Temporary Script
+      shell: bash
+      run: |
+        cat D:\a\_temp\32bbc863-5f2a-40d5-920b-c99877af7c9e.sh || echo "Script not found"
+
+
       - name: Install Building Dependencies
         if: steps.cache-WinDeps.outputs.cache-hit != 'true'
         shell: bash
@@ -70,9 +76,6 @@ jobs:
 
           # Extract the package
           7z x -y CrabNet.7z -oextern/raknet
-
-
-          cd C:\DreamWeave
 
           # Run the before script
           CI/before_script.msvc.sh -C -V -N -k -p Win64 -v 2022
